services:
  dev:
    image: cub3d-env
    build: .
    container_name: cub3d
    volumes:
      - ./:/home/student/project
      - ~/.Xauthority:/home/student/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=192.168.178.42:0
      - XAUTHORITY=/home/student/.Xauthority
      - LIBGL_ALWAYS_INDIRECT=1
      - XKB_DEFAULT_LAYOUT=us

    tty: true
    stdin_open: true
