services:
  dev:
    build: .
    container_name: cub3d
    
    platform: linux/amd64

    volumes:
      - ./:/home/student/project
    ports:
      - "5900:5900"
    environment:
      - DISPLAY=:0
    tty: true
    stdin_open: true
    command: >
      bash -c "
        Xvfb :0 -screen 0 1280x800x24 >/proc/1/fd/1 2>&1 &
        sleep 1
        fluxbox >/proc/1/fd/1 2>&1 &
        sleep 1
        exec x11vnc -display :0 -nopw -forever -shared -rfbport 5900 -noxdamage -o /proc/1/fd/1
      "