services:
  dev:
    image: cub3d-env
    build: .
    container_name: cub3d
    volumes:
      # Mount the project directory
      - ./:/home/student/project
      # Securely mount the X11 authentication cookie (NEW)
      - ~/.Xauthority:/home/student/.Xauthority:ro
    environment:
      # Point to the host display via network
      - DISPLAY=host.docker.internal:0
      # Point to the mounted authentication cookie (NEW)
      - XAUTHORITY=/home/student/.Xauthority
    tty: true
    stdin_open: true